//getFriends
export const GET_FRIENDS_START = 'GET_FRIENDS_START';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const GET_FRIENDS_FAILURE = 'GET_FRIENDS_FAILURE';

//change friend
export const CHANGE_FRIEND_START = 'CHANGE_FRIEND_START';
export const CHANGE_FRIEND_SUCCESS = 'CHANGE_FRIEND_SUCCESS';
export const CHANGE_FRIEND_FAILURE = 'CHANGE_FRIEND_FAILURE';

//delete friend
export const DELETE_FRIEND_START = 'DELETE_FRIEND_START';
export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS';
export const DELETE_FRIEND_FAILURE = 'DELETE_FRIEND_FAILURE';

//create new friend
export const CREATE_NEW_FRIEND_START = 'CREATE_NEW_FRIEND_START';
export const CREATE_NEW_FRIEND_SUCCESS = 'CREATE_NEW_FRIEND_SUCCESS';
export const CREATE_NEW_FRIEND_FAILURE = 'CREATE_NEW_FRIEND_FAILURE';