//getFriends
export const GET_FRIENDS_START = 'GET_FRIENDS_START';
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';
export const GET_FRIENDS_FAILURE = 'GET_FRIENDS_FAILURE';


export const CHANGE_FRIEND_START = 'CHANGE_FRIEND_START';
export const CHANGE_FRIEND_SUCCESS = 'CHANGE_FRIEND_SUCCESS';
export const CHANGE_FRIEND_FAILURE = 'CHANGE_FRIEND_FAILURE';


export const DELETE_FRIEND_START = 'DELETE_FRIEND_START';
export const DELETE_FRIEND_SUCCESS = 'DELETE_FRIEND_SUCCESS';
export const DELETE_FRIEND_FAILURE = 'DELETE_FRIEND_FAILURE';