export const AUTH_PERSON_START = 'AUTH_PERSON_START';
export const AUTH_PERSON_SUCCESS = 'AUTH_PERSON_SUCCESS';
export const AUTH_PERSON_FAILURE = 'AUTH_PERSON_FAILURE';
export const LOGOUT = 'LOGOUT';