export {
    AUTH_PERSON_START,
    AUTH_PERSON_SUCCESS,
    AUTH_PERSON_FAILURE,
    authPerson,
    GET_FRIENDS_START,
    GET_FRIENDS_SUCCESS,
    GET_FRIENDS_FAILURE,
    logout,
    goToFriend,
    CHANGE_FRIEND_START,
    CHANGE_FRIEND_SUCCESS,
    CHANGE_FRIEND_FAILURE,
    DELETE_FRIEND_START,
    DELETE_FRIEND_SUCCESS,
    DELETE_FRIEND_FAILURE
} from './personActions'